---
title: "Test Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Load packages ----
packages <- 
  c(
    "flexdashboard",
    "tidyverse",
    "googlesheets4",
    "flexdashboard",
    "plotly"
  )

lapply(
  packages,
  library,
  character.only = TRUE
)

# Disable authentication for the sheet
googlesheets4::gs4_deauth()
googlesheets4::gs4_auth()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, message=FALSE, include=FALSE}
# Make a function that reads the data
load_gsheet <- function(link, sheet_num){
  read_sheet(
    ss = link,
    sheet = sheet_num
  )
}

# Dilution test ----
## Load data ----
newMbF_dilute_gsheet <- 
  load_gsheet(
    link = "https://docs.google.com/spreadsheets/d/1PA8wqBVxadcV2PXCOSe4oeU_CkxvzuJIpHnMHTCX5Ss/edit#gid=0",
    sheet_num = 3
  ) |> 
  mutate(
    Datetime = paste(
      Date,
      hour(Time),
      minute(Time)
    ) |> 
      lubridate::ymd_hm()
  ) |> 
  dplyr::select(
    SampleID,
    Datetime,
    Dilution,
    OD600
  )  

# newMbF_dilute_gsheet <-
#   read_sheet(
#     ss = "https://docs.google.com/spreadsheets/d/1PA8wqBVxadcV2PXCOSe4oeU_CkxvzuJIpHnMHTCX5Ss/edit#gid=0",
#     sheet = 3
#   ) |>
#   mutate(
#     Datetime = paste(
#       Date,
#       hour(Time),
#       minute(Time)
#     ) |>
#       lubridate::ymd_hm()
#   ) |>
#   dplyr::select(
#     SampleID,
#     Datetime,
#     Dilution,
#     OD600
#   )

## Clean data ----
# get the initial date for each sample
dilute_init_date <- 
  newMbF_dilute_gsheet |> 
  group_by(SampleID, Dilution) |> 
  summarize(
    init_date = min(Datetime, na.rm = TRUE)
  ) |> 
  ungroup()
# select_init_date

# calculate time difference
dilute_clean_df <- 
  newMbF_dilute_gsheet |>  
  na.omit() |> 
  left_join(
    dilute_init_date,
    by = c("SampleID", "Dilution")
  ) |> 
  mutate(
    month = month(Datetime),
    day = day(Datetime)
  ) |> 
  # left_join(
  #   methane_gsheet |>
  #     mutate(
  #       month = month(Datetime),
  #       day = day(Datetime)
  #     ) |>
  #     dplyr::rename(
  #       methane_dttm = Datetime
  #     ),
  #   by = c(
  #     "SampleID", "MediaVersion", "month", "day", "OD600"
#   )
# ) |>
mutate(
  difftime = init_date - Datetime,
  difftime = `units<-.difftime`(difftime, "hours"),
  # difftime_methane = init_date - methane_dttm,
  # difftime_methane = `units<-.difftime`(difftime_methane, "hours")
)

## Visualize ----
### Set viz parameters ----
line_width <- 2
line_alpha <- 0.5
point_size <- 3
point_shape <- 21


line_col <- "grey88"
line_type <- "dashed"

### Make a theme for the OD graphs ----
od_theme <- 
  theme_set(
    theme_bw() +
      theme(
        axis.title.y = ggtext::element_markdown(),
        axis.ticks = element_line(
          color = line_col,
          linetype = line_type
        ),
        panel.grid = element_line(
          color = line_col,
          linetype = line_type
        ),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(
          face = "italic"
        ),
        strip.background = element_blank(),
        legend.position = "bottom"
      )
  )
# Visualize via ggplot
dilute_test_gg <- 
  dilute_clean_df |> 
  filter(SampleID %in% c("smt2*_1", "smt2*_2")) |> 
  mutate(
    Time = difftime |> as.numeric() |> abs() 
  ) |> 
  ggplot(
    mapping = aes(
      x = Time,
      y = OD600
    )
  ) +
  geom_line(
    mapping = aes(
      color = Dilution
    ),
    linewidth = line_width,
    alpha = line_alpha
  ) +
  geom_point(
    mapping = aes(
      fill = Dilution,
    ),
    shape = point_shape,
    size = point_size
  ) +
  labs(
    x = "Time (h)",
    y = "OD<sub>600</sub>",
    title = "New MbF - Dilution Test"
  ) +
  facet_grid(
    cols = vars(SampleID)
  ) +
  theme(od_theme)

dilute_test_gg |> 
  plotly::ggplotly()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

